AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating an S3 bucket'

Resources:
  MyS3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Sub '${AWS::StackName}-my-unique-bucket-name'
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref MyS3Bucket
  BucketARN:
    Description: 'ARN of the S3 bucket'
    Value: !GetAtt MyS3Bucket.Arn
