name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'  # or your preferred Java version
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests
      run: mvn test
